name: Build and deploy a container to DEV Azure Web App

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "dev" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log in to GitHub container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: hgmart
          password: ${{ secrets.HGMART_PAT }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Create Environment File
        run: |
          echo "DISABLE_DB=${{ vars.DISABLE_DB }}" > .env
          echo "DB_HOST=${{ vars.DB_HOST  }}" >> .env
          echo "DB_PORT=${{ vars.DB_PORT  }}" >> .env

      - name: Build and push container image to registry
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          push: false
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile
          context: .
