name: Tests coverage CI

on:
  push:
    branches: [ "dev", "coverage-con-pytest" ]
  pull_request:
    branches: [ "dev", "coverage-con-pytest" ]

jobs:
  coverall:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Install coverall
      run: |
        pip install coverage
        pip install coveralls

    - name: Calculate test coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coverage run -m pytest tests
        coveralls